accounts/urls.py
from django.urls import path, include
from main.views import index
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),

]

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls'),name='insta'),  # http://127.0.0.1:8000
    path('accounts/',include('accounts.urls'),name='accounts'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import index


app_name = 'insta' # front(html 파일)에서 url을 쉽게 조합하기 위해서도 사용됨

urlpatterns = [
    path('', index, name='index'),

]

accounts/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User # auth_user 테이블과 연결된 모델


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일") #기본 email의 형식 검사
    # last_name = forms.CharField(label='닉네임')
    last_name = forms.CharField(max_length=30, required=False)
    class Meta: # 클래스의 원천 클래스(클래스 설명 클래스) - 현 class가 연결해야할 model 정의
        model = User
        fields = ("username","last_name", "email",) # 사용할 필드면 명사(id, password는 기본 포함) - 필드명과 template에서 넘어오는 name 속성은 동일해야 함

accounts/views.py
from django.contrib.auth import authenticate, login #  login 모듈, authenticate 인증객체 생성
from django.shortcuts import render, redirect
from accounts.forms import UserForm

def signup(request):
    """
    계정생성
    """
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid(): # form의 접속이 유지되어 있으면
            form.save() # db에 저장
            # 가입한 회원으로 로그인 처리
            username = form.cleaned_data.get('username') # cleaned_data(네트워크 데이터가 아닌 db를 저장하기 위해 정제한 data)
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password ) # 인증객체 생성
            login(request, user) # 로그인 처리
            return redirect('http://127.0.0.1:8000') # main 컨텐츠 호출(authenticated 정보가 같이 전달됨)
    else:
        form = UserForm()
    return render(request, 'accounts/signup.html', {'form': form})

main/views.py
from django.shortcuts import render

# Create your views here.

def index(request) :
    return render(request, 'main/index.html')

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">


<!-- ------------------------------- [edit] -------------------------------- -->
    <div class="row">
        <div class="col-4"> <!-- 총 col을 12개로 분할하여 4만큼 차지-->
            <h4>로그인</h4>
        </div>
        <div class="col-8 text-right"> <!-- 총 col을 12개로 분할하여 8만큼 차지-->
            <span>또는 <a href="{% url 'accounts:signup' %}">계정을 만드세요.</a></span>
        </div>
    </div>
<!-- ----------------------------------------------------------------------- -->

    <form method="post" class="post-form" action="{% url 'accounts:login' %}">
        {% csrf_token %}
         <input type="hidden" name="next" value="{{ next }}">  <!-- 로그인 성공후 이동되는 URL -->
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="">
        </div>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
<!-- ------------------------------- [edit] -------------------------------- -->
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>계정생성</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'accounts:login' %}">로그인 하세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="username">닉네임</label>
            <input type="text" class="form-control" name="last_name" id="nick_name"
                   value="{{ form.last_name.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}
<!-- ----------------------------------------------------------------------- -->

config/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- jQuery JS -->
    <script src="{% static 'jquery-3.4.1.min.js' %}"></script>
    <!-- Bootstrap JS -->
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <title>Hello, insta</title>
</head>
<body>
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'insta:index' %}">INSTA</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                {% if user.is_authenticated %}
                 <a class="nav-link" href="{% url 'accounts:logout' %}">{{ user.username }} (로그아웃)</a>
                {% else %}
                <!-- ----------------------------------------------------------------------- -->
                    <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
                <!-- ------------------------------- [edit] -------------------------------- -->
                 {% endif %}
            </li>
        </ul>
    </div>
</nav>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>

config/templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. 필드값이 없을때 -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. 로그인 불가(회원이 아닐때) -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

config/templates/layout.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>Title</title>
    {%load static%}
    <link rel="stylesheet" href="{% static 'css/reset.css'%}">
    <link rel="stylesheet" href="{% static 'css/common.css'%}">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">


</head>
<body>
{%load static%}

<section id="container">


    <header id="header">
        <section class="inner">

            <h1 class="logo">
                <a href="index.html">
                    <div class="sprite_insta_icon"></div>
                    <div class="sprite_write_logo"></div>
                </a>
            </h1>

            <div class="search_box">
                <input type="text" placeholder="검색" id="search-field">

                <div class="fake_field">
                    <span class="sprite_small_search_icon"></span>
                    <span>검색</span>
                </div>
            </div>

            <div class="right_icons">
                <a href="new_post.html"><div class="sprite_camera_icon"></div></a>
                <a href="login.html"><div class="sprite_compass_icon"></div></a>
                <a href="follow.html"><div class="sprite_heart_icon_outline"></div></a>
                <a href="profile.html"><div class="sprite_user_icon_outline"></div></a>
            </div>

        </section>

    </header>
<!-- 각기 다른 content -->
    {% block content %}
    {% endblock %}
</section>

<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
<script src="js/main.js"></script>
</body>
</html>